blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('', views.ProductListView.as_view(), name='product-list-view'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('product_create/', views.ProductCreateView.as_view(), name='product-create'),
    path('product_update/<int:pk>', views.ProductUpdateView.as_view(), name='product-update'),
    path('product_delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product-delete'),
]

config/urls.py
from .settings import DEBUG
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include("catalog.urls", namespace="catalog")),
    path('blog/', include("blog.urls", namespace="blog"))
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    content = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(upload_to='blog_previews/', null=True, blank=True, verbose_name="Превью")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    views_count = models.IntegerField(default=0, verbose_name="Просмотры")

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ['title', ]

    def __str__(self):
        return self.title

catalog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=150, verbose_name = 'Название')
    description = models.TextField(verbose_name = 'Описание')
    

    def __str__(self):
        return f"{self.title}: {self.description}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ['title', ]

class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name = 'Название')
    description = models.TextField(verbose_name = 'Описание')
    image = models.ImageField(upload_to='product_image/', verbose_name = 'Изображение', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name = 'категория')
    price = models.IntegerField(verbose_name = 'Цена')
    updated_at = models.DateField(auto_now=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'''Название: {self.title}
        описание: {self.description}
        цена: {self.price}
        '''

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['title',]

catalog/forms.py
from django import forms
from .models import Product
from django.core.exceptions import ValidationError


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title','description', 'image', 'category', 'price']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите название товара'
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Подробное описание товара',
            'rows': 4
        })

        self.fields['price'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите цену'
        })

        self.fields['category'].widget.attrs.update({
            'class': 'form-select'
        })

        self.fields['image'].widget.attrs.update({
            'class': 'form-control'
        })

    def clean_title(self):
        title = self.cleaned_data.get('title')
        ban_words = ['казино','криптовалюта','крипта','биржа','дешево','бесплатно','обман','полиция','радар']
        if title.lower() in ban_words:
            raise ValidationError('В название есть запрещенные слова')
        return title

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 0:
            raise ValidationError('Цена может быть только больше нуля')
        return price

blog/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = Post.objects.all()
        if self.request.GET.get('published') == 'true':
            queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_published_filter'] = self.request.GET.get('published') == 'true'
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        post.views_count += 1
        post.save()
        return post


class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blog/post_create.html'
    success_url = reverse_lazy('blog:post_list')

class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blog/post_update.html'

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk': self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:post_list')

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import ProductForm
from .models import Product, Category
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:product-list-view')

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:product-list-view')

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'catalog/product_delete.html'
    success_url = reverse_lazy('catalog:product-list-view')

class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'

class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body class="bg-body-secondary">
    {% include 'blog/header.html' %}

    <main class="container mt-5">
        {% block content %}{% endblock %}
    </main>

    <script src="/static/scripts/bootstrap.bundle.js"></script>
</body>
</html>

blog/templates/blog/header.html
<header class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/blog/">Мои блоги</a>
        <nav class="d-flex gap-3">
            <a href="/catalog/" class="nav-link text-white">Магазин</a>
            <a href="/blog/" class="nav-link text-white">Мои блоги</a>
            <a href="/catalog/contacts/" class="nav-link text-white">Контакты</a>
        </nav>
    </div>
</header>

blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% block title %}Создание поста{% endblock %}

{% block content %}
<div class="card shadow-sm mx-auto" style="max-width: 700px;">
    <div class="card-body">
        <h2 class="card-title mb-4 text-center text-primary">Создать новый пост</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-3">
                    <label class="form-label fw-bold">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger small">{{ field.errors }}</div>
                    {% endif %}
                </div>
            {% endfor %}

            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-success px-4">Сохранить</button>
                <a href="{% url 'blog:post_list' %}" class="btn btn-outline-secondary px-4">Отмена</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}

{% block title %}Удаления блога{% endblock %}

{% block content %}
<h3>Удалить пост "{{ post.title }}"?</h3>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'blog:post_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="p-4 bg-light rounded shadow-sm">
    <h2 class="text-primary mb-4">{{ post.title }}</h2>

    {% if post.preview %}
        <img src="{{ post.preview.url }}" alt="{{ post.title }}" class="img-fluid rounded mb-3 shadow-sm">
    {% endif %}

    <h5 class="fw-bold">Содержимое блога:</h5>
    <div class="card mb-3">
        <div class="card-body">
            {{ post.content }}
        </div>
    </div>
    {% if post.is_published %}
        <span class="badge bg-success">Опубликован</span>
    {% else %}
        <span class="badge bg-secondary">Черновик</span>
    {% endif %}
    <p class="text-muted mb-0">Дата публикации: {{ post.created_at|date:"d.m.Y" }}</p>
    <p class="text-muted">Просмотров: {{ post.views_count }}</p>

    <div class="mt-3">
        <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-warning">Редактировать</a>
        <a href="{% url 'blog:post_list' %}" class="btn btn-outline-primary">Назад к списку</a>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}Блог{% endblock %}

{% block content %}

<h1 class="text-primary mb-3">Блоги</h1>

<div class="d-flex justify-content-between align-items-center mb-3">
    <div class="btn-group">
        <a href="{% url 'blog:post_list' %}?published=true"
           class="btn {% if is_published_filter %}btn-info{% else %}btn-outline-info{% endif %} btn-sm">
            Только опубликованные
        </a>

        <a href="{% url 'blog:post_list' %}"
           class="btn {% if not is_published_filter %}btn-info{% else %}btn-outline-info{% endif %} btn-sm">
            Все статьи
        </a>
    </div>

    <a href="{% url 'blog:post_create' %}" class="btn btn-success">
        + Создать пост
    </a>
</div>
<div class="row">
    {% for post in posts %}
    <div class="col-md-6 col-lg-4 mb-4">
        <div class="card shadow-sm h-100">
            {% if post.preview %}
                <img src="{{ post.preview.url }}" class="card-img-top img-fluid" alt="{{ post.title }}">
            {% else %}
                <img src="/static/img/no-image.jpg" class="card-img-top img-fluid" alt="Нет изображения">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text text-truncate">{{ post.content|truncatechars:100 }}</p>
                {% if post.is_published %}
                    <span class="badge bg-success">Опубликован</span>
                {% else %}
                    <span class="badge bg-secondary">Черновик</span>
                {% endif %}
                <div class="mt-3">
                    <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary btn-sm">Подробнее</a>
                    <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-warning btn-sm">Редактировать</a>
                    <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger btn-sm">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% if not posts %}
<div class="alert alert-info text-center">
    Пока нет постов.
</div>
{% endif %}
{% endblock %}

blog/templates/blog/post_update.html
{% extends 'blog/base.html' %}

{% block title %}Редактирование поста{% endblock %}

{% block content %}
<div class="card shadow-sm mx-auto" style="max-width: 700px;">
    <div class="card-body">
        <h2 class="card-title mb-4 text-center text-warning">Редактировать пост</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-3">
                    <label class="form-label fw-bold">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger small">{{ field.errors }}</div>
                    {% endif %}
                </div>
            {% endfor %}

            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-primary px-4">Сохранить</button>
                <a href="{% url 'blog:post_list' %}" class="btn btn-outline-secondary px-4">Отмена</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body class="bg-light">
    {% include 'catalog/header.html' %}

    <main class="container py-4">
        {% block content %}{% endblock %}
    </main>

    <script src="/static/scripts/bootstrap.bundle.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/scripts/bootstrap.bundle.js"></script>
</body>
</html>

catalog/templates/catalog/header.html
<header class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/catalog/">Магазин</a>
        <nav class="d-flex gap-3">
            <a href="/catalog/" class="nav-link text-white">Главная</a>
            <a href="/catalog/contacts/" class="nav-link text-white">Контакты</a>
        </nav>
    </div>
</header>

catalog/templates/catalog/product_delete.html
{% extends 'catalog/base.html' %}

{% block title %}Удаления продукта{% endblock %}

{% block content %}
<h3>Удалить товар "{{ product.title }}"?</h3>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'catalog:product-list-view' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
<div class="card shadow-sm">
    <div class="row g-0">
        <div class="col-md-5">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="{{ product.title }}">
            {% else %}
                <img src="/static/images/no-image.jpg" class="img-fluid rounded-start" alt="Нет изображения">
            {% endif %}
        </div>
        <div class="col-md-7">
            <div class="card-body">
                <h2 class="card-title mb-3 text-primary">{{ product.title }}</h2>
                <p class="card-text">{{ product.description|default:"Описание отсутствует" }}</p>
                <p class="h5 text-success mb-3">Цена: {{ product.price }} ₽ / шт.</p>
                <p class="text-muted">Категория: {{ product.category.title }}</p>
                <a href="/catalog/" class="btn btn-outline-primary mt-3">← Назад к каталогу</a>
                <a href="{% url 'catalog:product-update' product.pk %}" class="btn btn-outline-primary mt-3">Редактировать</a>
                <a href="{% url 'catalog:product-delete' product.pk %}" class="btn btn-outline-primary mt-3">Удалить</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block title %}Добавления продукта{% endblock %}

{% block content %}
<h2>{{ view.title }}</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex justify-content-between">
      <button type="submit" class="btn btn-success px-4">Сохранить</button>
      <a href="{% url 'catalog:product-list-view' %}" class="btn btn-outline-secondary px-4">Отмена</a>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<h2 class="mb-4 text-center text-primary fw-bold">Наши товары</h2>
<div class="d-flex justify-content-between align-items-center mb-4">
        <a href="{% url 'catalog:product-create' %}" class="btn btn-success">Добавить продукт</a>
</div>


<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for product in products %}
    <div class="col">
        <div class="card  h-100 shadow-sm">
            {% if product.image %}
               <img src="{{ product.image.url }}"
                 class="card-img-top"
                 style="height: 200px; width: 100%; object-fit: contain; background: #f8f9fa;">
            {% else %}
                <img src="/static/images/no-image.jpg" class="card-img-top" style="height: 200px;" alt="Нет изображения">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'catalog:product-detail' product.id %}" class="text-decoration-none text-dark">
                        {{ product.title|truncatechars:30 }}
                    </a>
                </h5>
                <p class="card-text small text-muted">{{ product.description|truncatechars:100 }}</p>
            </div>
            <div class="card-footer bg-white">
                <span class="fw-bold text-primary">{{ product.price }} ₽</span> <span class="text-muted">/ шт.</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/home.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<h2 class="mb-4 text-center text-primary fw-bold">Наши товары</h2>

<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for product in products %}
    <div class="col">
        <div class="card h-100 shadow-sm">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="card-img-top object-fit-cover" style="height: 200px;" alt="{{ product.title }}">
            {% else %}
                <img src="/static/images/no-image.jpg" class="card-img-top" style="height: 200px;" alt="Нет изображения">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'catalog:product_detail' product.id %}" class="text-decoration-none text-dark">
                        {{ product.title|truncatechars:30 }}
                    </a>
                </h5>
                <p class="card-text small text-muted">{{ product.description|truncatechars:100 }}</p>
            </div>
            <div class="card-footer bg-white">
                <span class="fw-bold text-primary">{{ product.price }} ₽</span> <span class="text-muted">/ шт.</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/product_details.html
{% extends 'base.html' %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
<div class="card shadow-sm">
    <div class="row g-0">
        <div class="col-md-5">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="{{ product.title }}">
            {% else %}
                <img src="/static/images/no-image.jpg" class="img-fluid rounded-start" alt="Нет изображения">
            {% endif %}
        </div>
        <div class="col-md-7">
            <div class="card-body">
                <h2 class="card-title mb-3 text-primary">{{ product.title }}</h2>
                <p class="card-text">{{ product.description|default:"Описание отсутствует" }}</p>
                <p class="h5 text-success mb-3">Цена: {{ product.price }} ₽ / шт.</p>
                <p class="text-muted">Категория: {{ product.category.title }}</p>
                <a href="/catalog/" class="btn btn-outline-primary mt-3">← Назад к каталогу</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}